[project]
name = "clrs"
version = "0.1.0"
description = "Exercises and implementations in C++/Rust of the algorithms from 'Introduction to Algorithms' (3e) -  Cormen, Leiserson, Rivest, & Stein"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "isort>=7.0.0",
    "pytest>=9.0.0",
    "ruff>=0.14.4",
    "ty>=0.0.5",
]
