[package]
name = "clrs_compruntime"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clrs_big_oh = { path = "../clrs_big_oh", version = "0.1.0" }
clrs_utils = { path = "../clrs_utils", version = "0.1.0" }
