name: Test C++ Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v7

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/cpp/build" >> "$GITHUB_OUTPUT"

    - name: Install Boost
      run: brew install boost

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=clang++
        -S ${{ github.workspace }}/cpp/

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }}

    - name: Test with CTest
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
