name: Format and Test Python Library with Ruff and Pytest 

on:
  push:
    branches: 
      - "main"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Format with ruff
        uses: astral-sh/ruff-action@v4.1.0
        with:
          src: py
          args: "format"

      - name: Fix with ruff
        uses: astral-sh/ruff-action@v4.1.0
        with:
          src: py
          args: "check --fix"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        working-directory: py
        run: uv python install 3.14

      - name: Sort imports with isort 
        working-directory: py
        run: uv run isort .

  test:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        working-directory: py
        run: uv python install 3.14

      - name: Test with pytest
        working-directory: py
        run: uv run -m pytest
